name: CI/CD Docker Deploy

# Запускать на пуш в ветку main или вручную
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Сборка и упаковка образа (ваш код) …

      - name: Setup SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ./ssh_key
          chmod 600 ./ssh_key

      - name: Copy image archive to VPS
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key_path: ./ssh_key
          source: 'my-svelte-app.tar.gz'
          target: '${{ secrets.TARGET_PATH }}'

      - name: Load image and restart container on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key_path: ./ssh_key
          script: |
            cd ${{ secrets.TARGET_PATH }}
            gzip -d my-svelte-app.tar.gz
            docker load < my-svelte-app.tar
            docker stop my-svelte-app || true
            docker rm my-svelte-app   || true
            docker run -d --name my-svelte-app -p 80:80 my-svelte-app:latest
            rm my-svelte-app.tar
