name: CI/CD Docker Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем код
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Сборка Docker образа
      - name: Build Docker image
        run: docker build -t my-svelte-app:latest .

      # 3. Упаковка образа
      - name: Save Docker image to tar.gz
        run: docker save my-svelte-app:latest | gzip > my-svelte-app.tar.gz

      # 4. Подготавливаем SSH-ключ
      - name: Setup SSH key
        run: |
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          sed -i 's/\r$//' ssh_key
          chmod 600 ssh_key

      # 5. Проверяем SSH-подключение
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i ssh_key \
            -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "echo SSH ok"

      # 6. Создаем папку на VPS (если нужно)
      - name: Ensure target dir exists
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i ssh_key \
            -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "mkdir -p ${{ secrets.TARGET_PATH }} && chown ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} ${{ secrets.TARGET_PATH }}"

      # 7. Копируем архив на VPS
      - name: Copy image archive via scp
        run: |
          scp -o StrictHostKeyChecking=no \
            -i ssh_key \
            -P ${{ secrets.SSH_PORT }} \
            my-svelte-app.tar.gz \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.TARGET_PATH }}

      # 8. Загружаем образ и перезапускаем контейнер
      - name: Load image & restart container
        run: |
          ssh -o StrictHostKeyChecking=no \
            -i ssh_key \
            -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "cd ${{ secrets.TARGET_PATH }} && \
             gzip -d my-svelte-app.tar.gz && \
             docker load < my-svelte-app.tar && \
             docker stop my-svelte-app || true && \
             docker rm my-svelte-app   || true && \
             docker run -d --name my-svelte-app -p 80:80 my-svelte-app:latest && \
             rm my-svelte-app.tar"
