name: CI/CD Docker Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-svelte-app:latest .

      - name: Save Docker image to tar.gz
        run: docker save my-svelte-app:latest | gzip > my-svelte-app.tar.gz

      - name: Setup SSH key
        run: |
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
          sed -i 's/\r$//' ssh_key
          chmod 644 ssh_key

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no \
              -i ssh_key \
              -p ${{ secrets.SSH_PORT }} \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
              "echo SSH connection successful"

      - name: Ensure TARGET_PATH exists on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key_path: ssh_key
          script: |
            mkdir -p ${{ secrets.TARGET_PATH }}
            chown ${{ secrets.SSH_USER }}:${{ secrets.SSH_USER }} ${{ secrets.TARGET_PATH }}

      - name: Copy image archive to VPS
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key_path: ssh_key
          source: my-svelte-app.tar.gz
          target: ${{ secrets.TARGET_PATH }}

      - name: Load image and restart container on VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key_path: ssh_key
          script: |
            cd ${{ secrets.TARGET_PATH }}
            gzip -d my-svelte-app.tar.gz
            docker load < my-svelte-app.tar
            docker stop my-svelte-app || true
            docker rm my-svelte-app   || true
            docker run -d --name my-svelte-app -p 80:80 my-svelte-app:latest
            rm my-svelte-app.tar
